version: 0.0.{build}
configuration: Release
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
before_build:
- cmd: nuget restore
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {

    .\Update-Nuspec.ps1 -version "$env:APPVEYOR_REPO_TAG_NAME"

    }
build:
  verbosity: detailed
  publish_nuget: true
test: off
assembly_info:
  patch: true
  file: \Objectivity.Bot.Utils\Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
environment:
  NugetApiKey:
    secure: Uv0dZyhFkHDm+qsH+qhtnM35q/U8pbVDBUWWlvP0VcCkOB26TOCDM+28wcVVKnao
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    api_key: $(NugetApiKey)
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true